### ISSUE TITLE
The indentation taking too long

### ISSUE THREAD

**Issue by chester755** [Wilfred/logstash-conf.el#5]
Hi, This is a great mode, I am currently using it for my config file, however, every indentation is taking too long to process.
The slow down is probably related to the fact that my conf file is too large, but I felt like this mode should be optimized for running relatively largely files as well right?

At the moment, every time I start a new line and press tab, it will take about 3-4 secs to finish, and I tried to indent a block of texts, it is just taking too long. Is there any way to optimize performance?

**Comment by Wilfred** [comment]
Do you have a sample file I can test with? Feel free to replace any values with placeholders.

**Comment by chester755** [comment]
Hi. sorry for this late reply, I have just drafted a test version in my git gist: [https://gist.github.com/chester755/daba9cd5f948e0e9d026841fbd82ffbe](url)
I think as the file is getting longer, it will take longer and longer to indent. In reality, I have a config file that is about several thousand lines long, this soon become a problem to indent.
